### ISSUE TITLE
Roll back org rename

### ISSUE THREAD

**Issue by aaronmondal** [nativelink/nativelink#997]
Virtually all our docs are broken since we changed the org name. Pipelines are also potentially affected. We need to migrate all references of `TraceMachina/nativelink`to `nativelink/nativelink` and coordinate the renames with other repositories like the `rules_mojo` repository whose docs were also broken by this.

For now we should roll back the rename and reevaluate whether this is really the right move. If we want to rename the org we should prepare renaming commits ahead of time and only do the rename in coordination with the doc updates as a breaking change.

cc @MarcusSorealheis @allada @nfarah86

**Comment by MarcusSorealheis** [comment]
Alright. Let's do it.
